GET localhost:8080/marketplace/api/product-offers?text=ар&limit=3&offset=2&order=store.rate

###
GET localhost:8080/marketplace/api/product-offers?filter=ар&order=aSc_product.rate

#добавить обработку параметра order выдавая отсортированный список
#GET /product-offers?text={text}&order={order)
#возможны варианты order
#
#    product-rate
#    organization-rate
#    price
