server:
  port: 8080
spring:
  mvc:
    servlet:
      path: /marketplace/api
  main:
    banner-mode: off
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        auto_quote_keyword: true
  datasource:
    url: jdbc:postgresql://localhost:5432/dbmarketplace2
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always