server:
  port: 8081
# JPA
spring:
  main:
    banner-mode: off
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  #  # H2
  #  h2.console.enabled: true
  #
  #  datasource:
  #    url: jdbc:h2:mem:testdb
  #    driverClassName: org.h2.Driver
  #    username: sa
  #    password: password

  datasource:
    url: jdbc:postgresql://localhost:5432/dbmarketplace2
    username: postgres
    password: polka
  sql:
    init:
      mode: always