name: Build

on:
  pull_request:
    branches:
      - 'telegram-bot-sprint1-cicd'
  push:
    branches:
      - 'telegram-bot-sprint1-cicd'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
      - name: Maven Package Core
        run: mvn -f core/pom.xml clean install -Dmaven.test.skip=true

      - name: Maven Package Telegrambot
        run: mvn -f telegrambot/pom.xml clean package -Dmaven.test.skip=true

      - name: Maven Package Website
        run: mvn -f website/pom.xml clean package -Dmaven.test.skip=true

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./telegrambot
          # Note: tags has to be all lower-case
          tags: |
            ru.teamtwo.telegrambot:latest
          # build on feature branches, push only on main branch
          # push: ${{ github.ref == 'refs/heads/main' }}
