name: Build

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
      - name: Maven Install Core
        run: mvn -f core/pom.xml clean install

      - name: Maven Package Telegrambot
        run: mvn -f telegrambot/pom.xml clean package

      - name: Maven Package Backend
        run: mvn -f api/pom.xml clean package

      - name: FTP Deploy Backend
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_LOGIN }}
          password: ${{ secrets.SERVER_PASSWORD }}
          local-dir: backend/
          server-dir: backend/
          exclude: |
            **/maven-archiver/**
            **/classes/**
            **/maven-status/**
            **/generated-sources/**
            **/src/**
            *.original
            .gitignore
            HELP.md
            pom.xml

      - name: FTP Deploy Telegrambot
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_LOGIN }}
          password: ${{ secrets.SERVER_PASSWORD }}
          local-dir: telegrambot/
          server-dir: telegrambot/
          exclude: |
            **/maven-archiver/**
            **/classes/**
            **/maven-status/**
            **/generated-sources/**
            **/src/**
            *.original
            .gitignore
            HELP.md
            pom.xml

      - name: SSH Build Docker API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_LOGIN }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: docker build backend -t teamtwo/backend:latest

      - name: SSH Build Docker Telegrambot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_LOGIN }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: docker build telegrambot -t teamtwo/telegrambot:latest

      - name: SSH Run Docker Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_LOGIN }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: docker run -d -p 8080:8080 --rm --name teamtwo_backend teamtwo/backend &

      - name: SSH Run Docker Telegrambot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_LOGIN }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: docker run -d --rm --name teamtwo_telegrambot teamtwo/telegrambot &
