name: Build

on:
  pull_request:
    branches:
      - 'telegram-bot-sprint1'
  push:
    branches:
      - 'telegram-bot-sprint1'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
      - name: Maven Install Core
        run: mvn -f core/pom.xml clean install -Dmaven.test.skip=true

      - name: Maven Package Telegrambot
        run: mvn -f telegrambot/pom.xml clean package -Dmaven.test.skip=true

      - name: Maven Package Website
        run: mvn -f website/pom.xml clean package -Dmaven.test.skip=true

      - name: FTP Deploy Website
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 62.109.17.193
          username: teamtwo
          password: teamtwo
          local-dir: website/
          server-dir: website/
          exclude: |
            **/maven-archiver/**
            **/classes/**
            **/maven-status/**
            **/generated-sources/**
            **/src/**
            *.original
            .gitignore
            HELP.md
            pom.xml

      - name: FTP Deploy Telegrambot
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 62.109.17.193
          username: teamtwo
          password: teamtwo
          local-dir: telegrambot/
          server-dir: telegrambot/
          exclude: |
            **/maven-archiver/**
            **/classes/**
            **/maven-status/**
            **/generated-sources/**
            **/src/**
            *.original
            .gitignore
            HELP.md
            pom.xml

      - name: SSH Build Docker Website
        uses: appleboy/ssh-action@master
        with:
          host: 62.109.17.193
          username: teamtwo
          password: teamtwo
          script: docker build website -t teamtwo/website:latest

      - name: SSH Build Docker Telegrambot
        uses: appleboy/ssh-action@master
        with:
          host: 62.109.17.193
          username: teamtwo
          password: teamtwo
          script: docker build telegrambot -t teamtwo/telegrambot:latest

      - name: SSH Run Docker Website
        uses: appleboy/ssh-action@master
        with:
          host: 62.109.17.193
          username: teamtwo
          password: teamtwo
          script: docker run teamtwo/website:latest -name teamtwo_website &

      - name: SSH Run Docker Telegrambot
        uses: appleboy/ssh-action@master
        with:
          host: 62.109.17.193
          username: teamtwo
          password: teamtwo
          script: docker run teamtwo/telegrambot:latest -name teamtwo_telegrambot &

