name: Build

on:
  pull_request:
    branches:
      - 'telegram-bot-sprint1'
  push:
    branches:
      - 'telegram-bot-sprint1'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
      - name: Maven Install Core
        run: mvn -f core/pom.xml clean install -Dmaven.test.skip=true

      - name: Maven Package Telegrambot
        run: mvn -f telegrambot/pom.xml clean package -Dmaven.test.skip=true

      - name: Maven Package Website
        run: mvn -f website/pom.xml clean package -Dmaven.test.skip=true

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Telegrambot Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./telegrambot
          tags: |
            ru.teamtwo.telegrambot:latest

      - name: Build Website Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./website
          tags: |
            ru.teamtwo.website:latest

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 62.109.17.193
          username: teamtwo
          password: teamtwo

      - name: SSH Run Docker Website
        uses: appleboy/ssh-action@master
        with:
          host: 62.109.17.193
          username: teamtwo
          password: teamtwo
          script: docker run --publish 8000:8000 website

      - name: SSH Run Docker Telegrambot
        uses: appleboy/ssh-action@master
        with:
          host: 62.109.17.193
          username: teamtwo
          password: teamtwo
          script: docker run --publish 8000:8000 telegrambot

